In [1]:
import pandas as pd

In [3]:
import numpy as np

In [5]:
import matplotlib.pyplot as pt

In [6]:
import seaborn as sns

In [17]:
df = pd.read_csv(r"D:\Data_Analytics\Final_Project\global_climate_change_extreme_weather_2026_new.csv")

In [18]:
df.head()

,record_id,country,region,avg_temperature_c,temperature_change_c,co2_emissions_mt,sea_level_rise_mm,flood_risk,drought_risk,heatwave_days,wildfire_incidents,rainfall_change_mm,air_quality_index,climate_risk_score,population_affected_m,year
0,CLM0001,Canada,North America,16.8,2.40,5477.0,1.44,Low,High,9.0,25.0,-117,127,89.0,92.7,2026
1,CLM0002,Brazil,South America,28.8,1.51,3758.0,1.55,Medium,Medium,38.0,197.0,73,103,81.0,95.4,2026
2,CLM0003,Australia,Oceania,6.6,1.70,1904.0,5.81,Medium,Medium,20.0,161.0,127,253,71.0,32.0,2026
3,CLM0004,Germany,Europe,10.9,1.53,3786.0,5.41,Medium,Low,56.0,191.0,-57,166,57.0,131.5,2026
4,CLM0005,United States,North America,13.9,2.07,732.0,3.20,High,High,42.0,76.0,-22,142,81.0,93.4,2026

In [20]:
df.shape

(5000, 16)

In [ ]:
# Dataset has 5000 rows and 16 columns in total

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   record_id              5000 non-null   str
 1   country                5000 non-null   str
 2   region                 5000 non-null   str
 3   avg_temperature_c      4998 non-null   float64
 4   temperature_change_c   4999 non-null   float64
 5   co2_emissions_mt       4997 non-null   float64
 6   sea_level_rise_mm      5000 non-null   float64
 7   flood_risk             5000 non-null   str
 8   drought_risk           5000 non-null   str
 9   heatwave_days          4998 non-null   float64
 10  wildfire_incidents     4999 non-null   float64
 11  rainfall_change_mm     5000 non-null   int64
 12  air_quality_index      5000 non-null   int64
 13  climate_risk_score     4999 non-null   float64
 14  population_affected_m  5000 non-null   float64
 15  year                   5000 non-null   int64
dtypes: float64(8), int64(3), str(5)
memory usage: 625.1 KB

In [ ]:
# Used df.info() to find the datatypes of each column.

In [22]:
df.describe()

,avg_temperature_c,temperature_change_c,co2_emissions_mt,sea_level_rise_mm,heatwave_days,wildfire_incidents,rainfall_change_mm,air_quality_index,climate_risk_score,population_affected_m,year
count,4998.000000,4999.000000,4997.000000,5000.00000,4998.000000,4999.000000,5000.000000,5000.000000,4999.000000,5000.000000,5000.0
mean,17.491457,1.493745,3144.870923,3.49663,32.410764,148.320864,0.881200,175.280200,57.597119,150.177160,2026.0
std,7.204215,0.576350,1640.154260,1.42864,16.262577,87.615682,86.708135,72.615251,22.030485,86.287074,0.0
min,5.000000,0.500000,301.000000,1.00000,5.000000,0.000000,-150.000000,50.000000,20.000000,1.100000,2026.0
25%,11.300000,0.990000,1708.000000,2.26000,18.000000,70.000000,-73.000000,112.000000,39.000000,78.200000,2026.0
50%,17.400000,1.480000,3171.000000,3.52000,32.000000,149.000000,2.000000,175.000000,58.000000,149.750000,2026.0
75%,23.800000,1.990000,4552.000000,4.74000,47.000000,223.000000,76.000000,239.000000,77.000000,225.025000,2026.0
max,30.000000,2.500000,5999.000000,6.00000,60.000000,300.000000,150.000000,300.000000,95.000000,300.000000,2026.0

In [ ]:
# df.describe() is used to find out the statistical summary of the dataset,

In [23]:
df

,record_id,country,region,avg_temperature_c,temperature_change_c,co2_emissions_mt,sea_level_rise_mm,flood_risk,drought_risk,heatwave_days,wildfire_incidents,rainfall_change_mm,air_quality_index,climate_risk_score,population_affected_m,year
0,CLM0001,Canada,North America,16.8,2.40,5477.0,1.44,Low,High,9.0,25.0,-117,127,89.0,92.7,2026
1,CLM0002,Brazil,South America,28.8,1.51,3758.0,1.55,Medium,Medium,38.0,197.0,73,103,81.0,95.4,2026
2,CLM0003,Australia,Oceania,6.6,1.70,1904.0,5.81,Medium,Medium,20.0,161.0,127,253,71.0,32.0,2026
3,CLM0004,Germany,Europe,10.9,1.53,3786.0,5.41,Medium,Low,56.0,191.0,-57,166,57.0,131.5,2026
4,CLM0005,United States,North America,13.9,2.07,732.0,3.20,High,High,42.0,76.0,-22,142,81.0,93.4,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CLM4996,Brazil,South America,18.4,1.84,3271.0,2.43,Medium,Low,52.0,161.0,129,76,57.0,116.6,2026
4996,CLM4997,Canada,North America,8.5,0.61,1252.0,1.59,Medium,High,59.0,16.0,-19,85,35.0,72.3,2026
4997,CLM4998,United Kingdom,Europe,19.4,1.76,5909.0,4.14,Medium,Low,5.0,31.0,114,282,83.0,256.8,2026
4998,CLM4999,China,Asia,13.7,0.71,3978.0,3.46,High,Medium,6.0,89.0,51,83,94.0,201.5,2026
4999,CLM5000,United Kingdom,Europe,7.2,2.45,2397.0,4.42,Low,Medium,52.0,287.0,23,152,49.0,19.1,2026

In [24]:
df.isnull().sum()

record_id                0
country                  0
region                   0
avg_temperature_c        2
temperature_change_c     1
co2_emissions_mt         3
sea_level_rise_mm        0
flood_risk               0
drought_risk             0
heatwave_days            2
wildfire_incidents       1
rainfall_change_mm       0
air_quality_index        0
climate_risk_score       1
population_affected_m    0
year                     0
dtype: int64